// ---------------------------------------------------------------------------
// kitn try — runner script generator + types
// ---------------------------------------------------------------------------

import { readConfig } from "../config/io.js";
import { NotInitializedError } from "../errors.js";

// ---------------------------------------------------------------------------
// Types (shared by CLI, MCP, and runner script)
// ---------------------------------------------------------------------------

export interface FieldInfo {
  type: "string" | "number" | "boolean" | "enum" | "object" | "array" | "unknown";
  description?: string;
  required: boolean;
  default?: unknown;
  options?: string[]; // for enum type
}

export interface TryListTool {
  name: string;
  description: string;
  schema: Record<string, FieldInfo>;
}

export interface TryListAgent {
  name: string;
  description: string;
  toolNames: string[];
}

export interface TryListResult {
  tools: TryListTool[];
  agents: TryListAgent[];
}

export interface AgentChatResponse {
  text: string;
  toolCalls: Array<{
    tool: string;
    input: Record<string, unknown>;
    result?: unknown;
  }>;
}

// ---------------------------------------------------------------------------
// Runner command helpers
// ---------------------------------------------------------------------------

export interface TryContext {
  cwd: string;
  runtime: string;
  baseDir: string;
}

/**
 * Read project config and return context needed for `kitn try`.
 */
export async function getTryContext(cwd: string): Promise<TryContext> {
  const config = await readConfig(cwd);
  if (!config) throw new NotInitializedError(cwd);
  return {
    cwd,
    runtime: config.runtime,
    baseDir: config.aliases.base ?? "src/ai",
  };
}

/**
 * Get runtime-specific command to execute the runner script.
 */
export function getRunnerCommand(runtime: string): string[] {
  switch (runtime) {
    case "bun":
      return ["bun"];
    case "deno":
      return ["deno", "run", "--allow-all"];
    case "node":
    default:
      return ["npx", "tsx"];
  }
}

/**
 * Path (relative to project root) where the runner script is written.
 */
export const RUNNER_PATH = ".kitn/try-runner.ts";

// ---------------------------------------------------------------------------
// Runner script source generator
// ---------------------------------------------------------------------------

/**
 * Generate the TypeScript source for the runner script.
 *
 * The runner is written into the user's project so it can resolve
 * `@kitn/*` path aliases and project-specific dependencies.
 * It communicates with the CLI/MCP via stdin/stdout JSON.
 */
export function generateRunnerScript(baseDir: string): string {
  // Runner lives at .kitn/try-runner.ts — one level deep from project root
  return `// Auto-generated by kitn CLI — do not edit
import "../${baseDir}/plugin.js";
import { ai } from "../${baseDir}/plugin.js";

// ── Zod schema serializer ──

function serializeSchema(schema: any): Record<string, any> {
  const fields: Record<string, any> = {};
  if (!schema || !schema.shape) return fields;

  for (const [key, field] of Object.entries<any>(schema.shape)) {
    fields[key] = serializeField(field);
  }
  return fields;
}

function serializeField(field: any): any {
  const info: any = {
    type: "unknown",
    required: true,
  };

  if (field.description) info.description = field.description;

  // Unwrap ZodOptional / ZodDefault
  let inner = field;
  const def = field?._zod?.def;

  if (def?.type === "optional") {
    info.required = false;
    inner = def.innerType;
  } else if (def?.type === "default") {
    info.required = false;
    info.default = typeof def.defaultValue === "function" ? def.defaultValue() : def.defaultValue;
    inner = def.innerType;
  }

  // Unwrap again if optional wraps default or vice versa
  const innerDef = inner?._zod?.def;
  if (innerDef?.type === "optional") {
    info.required = false;
    inner = innerDef.innerType;
  } else if (innerDef?.type === "default") {
    info.required = false;
    if (!("default" in info)) {
      info.default = typeof innerDef.defaultValue === "function" ? innerDef.defaultValue() : innerDef.defaultValue;
    }
    inner = innerDef.innerType;
  }

  // Preserve description from inner type if not already set
  if (!info.description && inner?.description) {
    info.description = inner.description;
  }

  const resolvedDef = inner?._zod?.def;
  const resolvedType = resolvedDef?.type;

  switch (resolvedType) {
    case "string":
      info.type = "string";
      break;
    case "number":
    case "int":
      info.type = "number";
      break;
    case "boolean":
      info.type = "boolean";
      break;
    case "enum": {
      info.type = "enum";
      // Zod v4 enums: entries is Record<string, string>
      const entries = resolvedDef.entries;
      if (entries && typeof entries === "object") {
        info.options = Object.values(entries);
      } else if (resolvedDef.values) {
        info.options = resolvedDef.values;
      }
      break;
    }
    case "object":
      info.type = "object";
      break;
    case "array":
      info.type = "array";
      break;
    default:
      info.type = "string"; // fallback
      break;
  }

  return info;
}

// ── Commands ──

const cmd = JSON.parse(process.argv[2] ?? "{}");

async function main() {
  switch (cmd.cmd) {
    case "list": {
      const tools = ai.tools.list().map((t: any) => ({
        name: t.name,
        description: t.description,
        schema: serializeSchema(t.inputSchema),
      }));
      const agents = ai.agents.list().map((a: any) => ({
        name: a.name,
        description: a.description,
        toolNames: a.toolNames ?? [],
      }));
      process.stdout.write(JSON.stringify({ tools, agents }) + "\\n");
      break;
    }

    case "exec-tool": {
      const result = await ai.tools.execute(cmd.name, cmd.input);
      process.stdout.write(JSON.stringify({ result }) + "\\n");
      break;
    }

    case "agent-chat": {
      const agent = ai.agents.get(cmd.name);
      if (!agent) {
        process.stdout.write(JSON.stringify({ error: "Agent not found: " + cmd.name }) + "\\n");
        process.exit(1);
      }

      // Import runAgent from @kitn/core
      const { runAgent } = await import("@kitn/core");

      const messages: Array<{ role: "user" | "assistant"; content: string }> = [];
      const { createInterface } = await import("readline");
      const rl = createInterface({ input: process.stdin, terminal: false });

      for await (const line of rl) {
        const userMessage = line.trim();
        if (!userMessage) continue;

        messages.push({ role: "user", content: userMessage });

        try {
          const result = await runAgent(
            ai,
            {
              system: agent.defaultSystem,
              tools: agent.tools ?? {},
              agentName: agent.name,
            },
            messages,
          );

          // Extract tool calls from the result
          const toolCalls = result.toolsUsed.map((name: string) => ({
            tool: name,
            input: {},
          }));

          messages.push({ role: "assistant", content: result.response });

          const response: any = {
            text: result.response,
            toolCalls,
          };
          process.stdout.write(JSON.stringify(response) + "\\n");
        } catch (err: any) {
          const response: any = {
            text: "Error: " + (err.message ?? String(err)),
            toolCalls: [],
          };
          process.stdout.write(JSON.stringify(response) + "\\n");
        }
      }
      break;
    }

    default:
      process.stderr.write("Unknown command: " + JSON.stringify(cmd) + "\\n");
      process.exit(1);
  }
}

main().catch((err) => {
  process.stderr.write("Runner error: " + (err.message ?? String(err)) + "\\n");
  process.exit(1);
});
`;
}
