// Re-export types, pure functions, and I/O functions from cli-core
export {
  installedComponentSchema,
  type RegistryEntry,
  type RegistryValue,
  DEFAULT_REGISTRY_URL,
  DEFAULT_REGISTRIES,
  DEFAULT_ALIASES,
  configSchema,
  type KitnConfig,
  getRegistryUrl,
  resolveRoutesAlias,
  lockSchema,
  type LockFile,
  CONFIG_FILE,
  LOCK_FILE,
  getInstallPath,
  readConfig,
  writeConfig,
  readLock,
  writeLock,
} from "@kitnai/cli-core";
